env:
  browser: true
  es2021: true
extends:
  - standard
  - 'plugin:react/recommended'
  - 'plugin:react/jsx-runtime'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2

# Enable jest linting on only test files
overrides:
  - files: 
      - '**/*.test.tsx'
    env:
      jest: true
    plugins:
      - jest

